workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

variables:
  DOCKER_REPOSITORY: <dockerhub_username>/worklog-backend

stages:
  - init
  - test
  - build
  - deploy
  - notify

init:
  stage: init
  image: alpine:latest
  script:
    - echo "FULL_SHA=${CI_COMMIT_SHA}" >> build.env
    - echo "SHORT_SHA=$(echo ${CI_COMMIT_SHA} | cut -c1-8)" >> build.env
    - echo "BRANCH=${CI_COMMIT_BRANCH}" >> build.env
    - echo "COMMIT_MESSAGE=$(echo ${CI_COMMIT_MESSAGE} | head -1)" >> build.env
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env

test:
  stage: test
  image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
  needs:
    - init
  script:
    - echo "let's run a test for ${SHORT_SHA} in ${BRANCH}"
    - uv sync --extra dev
    - TESTING=true uv run coverage run --source ./src/worklog -m pytest --disable-warnings -v
    - uv run coverage report

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  needs:
    - init
    - test
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_CONFIG: "/tmp/docker_config"
  script:
    - echo "Let's build the image for ${FULL_SHA}"
    - echo "The change commit message to build is '${COMMIT_MESSAGE}'"
    - echo ${DOCKERHUB_TOKEN} | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
    - docker buildx rm mybuilder 2>/dev/null || true
    - docker buildx create --name mybuilder --driver docker-container --use
    - docker buildx build --platform linux/amd64,linux/arm64
        -t ${DOCKER_REPOSITORY}:${FULL_SHA}
        -t ${DOCKER_REPOSITORY}:${SHORT_SHA}
        --push .
    - echo "build successful and published image with the following tags:"
    - echo "Tags:${SHORT_SHA}, ${FULL_SHA}"

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  needs:
    - init
    - build
  script:
    - echo "Let's deploy the image"
    - echo "Deploying our image ${FULL_SHA} to the cluster"
    - mkdir -p ~/.kube
    - echo "${CP_K8S_CONTEXT}" > ~/.kube/config
    - kubectl apply -f deploy_manifest/worklog-backend.yaml

notify-success:
  stage: notify
  needs:
    - init
    - build
    - deploy
  script:
    - echo "Your pipeline has been completed"
    - echo "Commit Message:${COMMIT_MESSAGE}"
    - echo "Tags:${SHORT_SHA}, ${FULL_SHA}"
  rules:
    - when: on_success

notify-failure:
  stage: notify
  needs:
    - init
    - build
    - deploy
  script:
    - echo "Your pipeline has been failed"
    - echo "Commit Message:${COMMIT_MESSAGE}"
    - echo "Tags:${SHORT_SHA}, ${FULL_SHA}"
  rules:
    - when: on_failure
