apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worklog-backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<github_username>/worklog-backend.git
    targetRevision: develop
    path: deploy_manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worklog-backend-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<github_username>/worklog-backend.git
    targetRevision: release/1.0.0
    path: deploy_manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worklog-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<github_username>/worklog-backend.git
    targetRevision: main
    path: deploy_manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
