apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: worklog-backend
  template:
    metadata:
      labels:
        app: worklog-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: worklog-backend
          image: <dockerhub_username>/worklog-backend:<image_tag>
          ports:
            - containerPort: 80
          env:
            - name: MONGO_HOST
              value: worklog-mongodb.default.svc.cluster.local
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: worklog-mongodb-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worklog-mongodb-creds
                  key: password
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
