apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: worklog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklog-backend
  template:
    metadata:
      labels:
        app: worklog-backend
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: worklog-backend
        image: <dockerhub_username>/worklog-backend:<image_tag>
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: worklog-mongodb.default.svc.cluster.local
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: worklog-mongodb-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: worklog-mongodb-creds
              key: password
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      analysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: worklog-backend
