stages:
  - test
  - build
  - deploy

variables:
  DOCKER_REPOSITORY: worklog-backend
  ARGOCD_SERVER: argocd.myk8s.local

.determine-environment: &determine-environment
  - |
    if [[ "$CI_COMMIT_TAG" =~ ^v ]]; then
      export TARGET_ENV=prod
      export ARGOCD_APP=worklog-backend-prod
    elif [[ "$CI_COMMIT_BRANCH" =~ ^release/ ]]; then
      export TARGET_ENV=staging
      export ARGOCD_APP=worklog-backend-staging
    else
      export TARGET_ENV=dev
      export ARGOCD_APP=worklog-backend-dev
    fi

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /^release\//
    - if: $CI_COMMIT_TAG =~ /^v/

test:
  stage: test
  image: python:3.12.3-slim-bookworm
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  needs: [test]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - docker build -t $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA .
    - docker push $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA

deploy:
  stage: deploy
  image: argoproj/argocd:latest
  needs: [build]
  before_script:
    - *determine-environment
  script:
    - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure
    - argocd app set $ARGOCD_APP --parameter image.tag=$SHORT_SHA
    - argocd app sync $ARGOCD_APP
    - argocd app wait $ARGOCD_APP --health
