FROM jenkins/inbound-agent:3248.v65ecb_254c298-3-jdk17

USER root
# Install docker
RUN apt-get update \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo \
       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
       $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
       tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce
# Ensure to have the same docker GID(998) between the host and container
RUN groupmod -g 900 systemd-network \
    && groupmod -g 998 docker \
    && usermod -aG docker jenkins
USER jenkins
