name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  init-and-test:
    runs-on: ubuntu-latest
    outputs:
      full_sha: ${{ steps.vars.outputs.full_sha }}
      short_sha: ${{ steps.vars.outputs.short_sha }
      branch: ${{ steps.vars.outputs.branch }
    steps:
      - uses: actions/checkout@v4
      - id: vars
        name: init variables
        run: |
          full_sha=${{ github.sha }}
          short_sha=$(echo ${full_sha} | cut -c1-8)
          branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')

          # Export slack vars to outputs
          echo "full_sha=${full_sha}" >> $GITHUB_OUTPUT
          echo "short_sha=${short_sha}" >> $GITHUB_OUTPUT
          echo "branch=${branch}" >> $GITHUB_OUTPUT
      - name: Notify starting
        run: |
          echo "Sending a 'start' notification to Slack for build ${{ steps.vars.outputs.short_sha }}"
      - name: Run test
        run: |
          echo "let's run test for ${{ steps.vars.outputs.short_sha }} in ${{ steps.vars.output.branch }}"
          echo "running test for ${{ steps.vars.outputs.full_sha }}"
          echo "Test Passed!"
  build:
    runs-on: ubuntu-latest
    needs: [init-and-test]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          echo "Let's build the image for ${{ needs.init-and-test.outputs.full_sha }}"
          echo "build successful and published image with the following tags:"
          echo "Tags: ${{ needs.init-and-test.outputs.full_sha }}, ${{ needs.init-and-test.outputs.short_sha }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [init-and-test, build]
    steps:
      - name: Build image
        run: |
          echo "Let's deploy the image"
          echo "Deploying our image ${{ needs.init-and-test.outputs.full_sha }} to the cluster"

  notify-success-result:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [init-and-test]
    steps:
      - name: Slack Notification Success
        run: |
          echo "Your deployment has been completed"
          echo "Tags: ${{ needs.init-and-test.outputs.full_sha }}, ${{ needs.init-and-test.outputs.short_sha }}"

  notify-failure-result:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [init-and-test]
    steps:
      - name: Slack Notification Failure
        run: |
          echo "Your pipeline has been failed"
          echo "Tags: ${{ needs.init-and-test.outputs.full_sha }}, ${{ needs.init-and-test.outputs.short_sha }}"
