apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
  template.app-sync-succeeded: |
    message: |
      :white_check_mark: Application *{{.app.metadata.name}}* sync succeeded.
      Revision: {{.app.status.sync.revision}}
      Time: {{now | date "2006-01-02 15:04:05"}}
  template.app-sync-failed: |
    message: |
      :x: Application *{{.app.metadata.name}}* sync failed.
      Revision: {{.app.status.sync.revision}}
      Time: {{now | date "2006-01-02 15:04:05"}}
  trigger.on-sync-succeeded: |
    - send: [app-sync-succeeded]
      when: app.status.operationState.phase in ['Succeeded']
  trigger.on-sync-failed: |
    - send: [app-sync-failed]
      when: app.status.operationState.phase in ['Error', 'Failed']
  defaultTriggers: |
    - on-sync-succeeded
    - on-sync-failed
