apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-backend
spec:
  selector:
    matchLabels:
      app: worklog-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: worklog-backend
        image: worklog-backend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: worklog-backend
  labels:
    app: worklog-backend
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worklog-backend
spec:
  ingressClassName: nginx
  rules:
  - host: worklog-backend.myk8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
