apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-frontend
spec:
  selector:
    matchLabels:
      app: worklog-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: worklog-frontend
    spec:
      containers:
      - name: worklog-frontend
        image: sungminl/worklog-frontend:buildtest1
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: http://worklog-backend.default.svc.cluster.local:80
---
apiVersion: v1
kind: Service
metadata:
  name: worklog-frontend
  labels:
    app: worklog-frontend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 5173
  selector:
    app: worklog-frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worklog-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: worklog-frontend.myk8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: worklog-frontend
            port:
              number: 80
