apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-backend
spec:
  selector:
    matchLabels:
      app: worklog-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: worklog-backend
    spec:
      containers:
      - name: worklog-backend
        image: sungminl/worklog-backend:buildtest1
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: worklog-mongodb.default.svc.cluster.local
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mypassw0rd
---
apiVersion: v1
kind: Service
metadata:
  name: worklog-backend
  labels:
    app: worklog-backend
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: worklog-backend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worklog-backend
spec:
  ingressClassName: nginx
  rules:
  - host: worklog-backend.myk8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: worklog-backend
            port:
              number: 80
