name: worklog backend pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_REPOSITORY: sungminl/worklog-backend
  DOCKERHUB_USERNAME: sungminl
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  init-and-test:
    runs-on: ubuntu-latest
    outputs:
      full_sha: ${{ steps.vars.outputs.full_sha }}
      short_sha: ${{ steps.vars.outputs.short_sha }}
      branch: ${{ steps.vars.outputs.branch }}
      commit_message: ${{ steps.vars.outputs.commit_message }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - id: vars
        name: init variables
        run: |
          full_sha=${{ github.sha }}
          short_sha=$(echo ${full_sha} | cut -c1-8)
          branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          commit_message=$(git log -1 --format="*%s* by _%an_")

          # Export slack vars to outputs
          echo "full_sha=${full_sha}" >> $GITHUB_OUTPUT
          echo "short_sha=${short_sha}" >> $GITHUB_OUTPUT
          echo "branch=${branch}" >> $GITHUB_OUTPUT
          echo "commit_message=${commit_message}" >> $GITHUB_OUTPUT
      - name: Notify starting
        run: |
          echo "Sending a 'start' notification to Slack for build ${{ steps.vars.outputs.short_sha }}"
      - name: Run test
        run: |
          echo "let's run a test for ${{ steps.vars.outputs.short_sha }} in ${{ steps.vars.output.branch }}"
          echo "running test for ${{ steps.vars.outputs.full_sha }}"
          pip install poetry
          poetry install --no-root
          export TESTING=true
          poetry run coverage run --source ./src/worklog -m pytest --disable-warnings -v
          poetry run coverage report
  build:
    runs-on: ubuntu-latest
    needs: [init-and-test]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          echo "Let's build the image for ${{ needs.init-and-test.outputs.full_sha }}"
          echo "The change commit message to build is '${{ needs.init-and-test.outputs.commit_message }}'"
          echo ${{ env.DOCKERHUB_TOKEN }} | docker login --username ${{ env.DOCKERHUB_USERNAME }} --password-stdin
          docker build . \
            -t ${{ env.DOCKER_REPOSITORY }}:${{ needs.init-and-test.outputs.full_sha }} \
            -t ${{ env.DOCKER_REPOSITORY }}:${{ needs.init-and-test.outputs.short_sha }}
          docker push ${{ env.DOCKER_REPOSITORY }}:${{ needs.init-and-test.outputs.short_sha }}
          docker push ${{ env.DOCKER_REPOSITORY }}:${{ needs.init-and-test.outputs.full_sha }}
          echo "build successful and published image with the following tags:"
          echo "Tags: ${{ needs.init-and-test.outputs.short_sha }}, ${{ needs.init-and-test.outputs.full_sha }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [init-and-test, build]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy image
        run: |
          echo "Let's deploy the image"
          echo "Deploying our image ${{ needs.init-and-test.outputs.full_sha }} to the cluster"
          kubectl apply -f deploy_manifest/worklog-backend.yaml

  notify-success-result:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [init-and-test, build, deploy]
    steps:
      - name: Slack Notification Success
        run: |
          echo "Your pipeline has been completed"
          echo "Commit Message: ${{ needs.init-and-test.outputs.commit_message }}"
          echo "Tags: ${{ needs.init-and-test.outputs.short_sha }}, ${{ needs.init-and-test.outputs.full_sha }}"

  notify-failure-result:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [init-and-test, build, deploy]
    steps:
      - name: Slack Notification Failure
        run: |
          echo "Your pipeline has been failed"
          echo "Commit Message: ${{ needs.init-and-test.outputs.commit_message }}"
          echo "Tags: ${{ needs.init-and-test.outputs.short_sha }}, ${{ needs.init-and-test.outputs.full_sha }}"
