workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - build
  - deploy

variables:
  DOCKER_REPOSITORY: worklog-frontend

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - docker build -t $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA .
    - docker push $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - mkdir -p $HOME/.kube
    - echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
  script:
    - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - kubectl set image deployment/worklog-frontend
        worklog-frontend=$DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA
