workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - build
  - deploy

variables:
  DOCKER_REPOSITORY: worklog-backend

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - docker build -t $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA .
    - docker push $DOCKERHUB_USERNAME/$DOCKER_REPOSITORY:$SHORT_SHA

deploy:
  stage: deploy
  image: argoproj/argocd:latest
  needs: [build]
  script:
    - SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure
    - argocd app set worklog-backend --parameter image.tag=$SHORT_SHA
    - argocd app sync worklog-backend
    - argocd app wait worklog-backend --health
