apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: worklog-backend
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: worklog-backend
  template:
    metadata:
      labels:
        app: worklog-backend
    spec:
      containers:
        - name: worklog-backend
          image: <dockerhub_username>/worklog-backend:buildtest1
          ports:
            - containerPort: 8000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 30s}
        - setWeight: 60
        - pause: {duration: 30s}
        - setWeight: 80
        - pause: {duration: 30s}
